name: "Secret Scan"

on: [push, pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Gitleaks
      uses: zricethezav/gitleaks-action@master
